#!/usr/bin/env bash
# Switch to my main branch and pull any changes from the remote.

set -o errexit
set -o nounset

# Checking for the branch first is a bit slower, but avoids a potentially
# confusing warning immediately before the pull:
#
#     Already on 'main'
#     Your branch is up to date with 'origin/main'.
#
if [[ $(gcb) != $(_get_primary_branch) ]]
then
  print_info "-> git checkout $(_get_primary_branch) (was on $(gcb))"
  git checkout "$(_get_primary_branch)"
  echo ""
fi

# This avoids any clashes with other programs called "gp", e.g. at one
# point I had gitpython in my PATH
$(dirname "$0")/gp

echo ""

cleanup_branches
