#!/usr/bin/env bash
# Pull any changes from the remote Git server.

set -o errexit
set -o nounset

_ensure_ssh_key_loaded

HEAD="$(git rev-parse --abbrev-ref HEAD)"

# This avoids any clashes with other programs called "gp", e.g. at one
# point I had gitpython in my PATH
$(dirname "$0")/gf

echo ""

if [[ "${1:-}" == "--rebase" ]]
then
  print_info "-> git rebase $HEAD"
  git rebase "origin/$HEAD"
else
  print_info "-> git merge $HEAD"
  git merge "origin/$HEAD"
fi
