#!/usr/bin/env bash
# Pull any changes from the remote Git server.

set -o errexit
set -o nounset

_ensure_ssh_key_loaded

HEAD="$(git rev-parse --abbrev-ref HEAD)"

gf

if [[ "${1:-}" == "--rebase" ]]
then
  print_info "-> git rebase $HEAD"
  git rebase "$HEAD"
else
  print_info "-> git merge $HEAD"
  git merge "$HEAD"
fi
