#!/usr/bin/env bash
# Open the current Git repo in my web browser (assuming it's a GitHub repo).

set -o errexit
set -o nounset

# The remote URL will be something of the form
#
#     git@github.com:alexwlchan/photo-reviewer.git
#
# The tr/awk gets everything after the colon, then prepends github.com.
open https://github.com/$(git remote get-url origin | tr ':' ' ' | awk '{print $2}')
