#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o verbose

aws-azure-login --no-prompt
AWS_PROFILE=experience-dev aws ecr-public --region=us-east-1 get-login-password | docker login --username AWS --password-stdin public.ecr.aws