#!/usr/bin/env bash

set -o errexit
set -o nounset

NAME="$1"

# Add the new library to requirements.in
pip freeze | grep "$NAME" >> requirements.in

# Now sort the file
sort requirements.in > requirements.in.tmp
mv requirements.in.tmp requirements.in

# And rebuild the requirements.txt
pip-compile
