#!/usr/bin/env bash
# This is a shortcut for 'mv' that I use for filing documents.
#
# I have a 'screenshots' directory that's divided into years; running
# `screenshot image.png` will move it to the appropriate folder for
# the current year.
#
# See also: 'fun', 'wellcome'

_file_by_year "/Volumes/Media (Sapphire)/screenshots" "$@"
