#!/usr/bin/env bash

set -o errexit
set -o nounset

export FLICKR_API_KEY=$(keyring get flickr_api key)

ruff check .
ruff format --check .

mypy src tests

coverage run -m pytest tests
coverage report
