#!/usr/bin/env bash

set -o errexit
set -o nounset

export FLICKR_API_KEY=$(keyring get flickr_api key)

black .
flake8 --exclude .venv --ignore=E501,E203,W503 --extend-select=W504

mypy src tests

coverage run -m pytest tests
coverage report
