#!/usr/bin/env bash
# This is an alias for "terraform init".

set -o errexit
set -o nounset

tf init "$@"

# Tell Time Machine that it doesn't need to both backing up the
# .terraform directory.
if [[ -d ".terraform" ]]
then
  tmutil addexclusion .terraform
fi
