#!/usr/bin/env osascript -l JavaScript
// A script to close ephemeral Safari tabs.
//
// This is a script I run at the end of each working day, to close
// Safari tabs I've opened that can be safely closed.
//
// See https://alexwlchan.net/2022/safari-tabs/

safari = Application("Safari");

// Generates all the window/tab/URLs in Safari.
//
// This runs in reverse window/tab index order: that is, windows are returned
// bottom to top, and tabs from right to left.
function* tabGenerator() {
  window_count = safari.windows.length;

  for (window_index = window_count - 1; window_index >= 0; window_index--) {
    window = safari.windows[window_index];

    tab_count = window.tabs.length;

    for (tab_index = tab_count - 1; tab_index >= 0; tab_index--) {
      tab = window.tabs[tab_index];
      yield [window_index, tab_index, tab.url()];
    }
  }
}

function isSafeToClose(url) {

  // Sometimes we get a `null` as the URL of a tab; I'm not sure why,
  // so leave this tab open.
  if (url === null) { return false; }

  return (
    url.startsWith("http://localhost:3000/") ||
    url.startsWith("https://app.fastmail.com/mail/Inbox/?u=") ||
    url.startsWith("https://github.com/Flickr-Foundation/") ||
    url.startsWith("https://zoom.us/")
  ) || (
    url === 'https://alexwlchan.net/' ||
    url === 'https://arstechnica.com/' ||
    url === 'https://github.com/' ||
    url === 'https://github.com/alexwlchan/scripts' ||
    url === 'https://mail.google.com/mail/u/0/#inbox' ||
    url === 'https://mobile.twitter.com/home' ||
    url === 'https://news.ycombinator.com/' ||
    url === 'https://remote.com' ||
    url === 'https://social.alexwlchan.net/home' ||
    url === 'https://twitter.com/home' ||
    url === 'https://twitter.com/i/timeline' ||
    url === 'https://twitter.com/notifications' ||
    url === 'https://www.facebook.com/' ||
    url === 'https://www.macrumors.com' ||
    url === 'https://www.theguardian.com/uk' ||
    url === 'https://www.youtube.com/'
  );
}

let closedCount = 0;
let remainingCount = 0;

for (const [window_index, tab_index, url] of tabGenerator()) {
	if (isSafeToClose(url)) {
		console.log(url);
		safari.windows[window_index].tabs[tab_index].close();
    closedCount += 1;
	} else {
	  remainingCount += 1;
	}
}

console.log(`Closed ${closedCount} tab${closedCount !== 1 ? 's' : ''}; ${remainingCount} tab${remainingCount !== 1 ? 's' : ''} left open`)
