#!/usr/bin/env osascript -l JavaScript
// Counts the number of windows I have open in Safari.

const safari = Application("Safari");

var totalTabs = 0;

const windowCount = safari.windows.length;

for (index = 0; index < safari.windows.length; index++) {
  totalTabs += safari.windows[index].tabs.length;
}

if (totalTabs === 1) {
  'There is 1 tab open.';
} else {
  `There are ${totalTabs} tabs open.`;
}
