#!/usr/bin/env osascript -l JavaScript
// Given the name of an app, print the title of the frontmost window
// in that app.
//
// Examples:
//
//      $ get_frontmost_window_title "Obsidian"
//      Short story ideas - textfiles - Obsidian v1.4.16
//
//      $ get_frontmost_window_title "TextMate"
//      get_frontmost_window_title — macos (git: main)
//
// This is particularly useful for writing automations for apps that
// don't support AppleScript.

function run(argv) {
  if (argv.length !== 1) {
    throw new Error("Usage: get_frontmost_window_title <APP_NAME>")
  }

  const appName = argv[0];

  const systemEvents = Application("System Events");
  const process = systemEvents.processes[appName];

  if (process.windows.length > 0) {
    return process.windows[0].name();
  } else {
    throw new Error(`No windows open in ${appName}!`);
  }
}
