#!/usr/bin/env bash
# Prints the path to the note I currently have open in Obsidian (if any).
#
# This relies on knowing the on-disk locations of my Obsidian vaults,
# so you won't be able to use this without changing it for your own setup.
# Add the path to your vaults in the `case` statement below.

set -o errexit
set -o nounset

window_title=$(osascript -e '
  tell application "System Events"
      tell process "Obsidian" to get title of front window
  end tell
')

# The window title will be a three part string of the form
#
#     Note title - Vault name - Obsidian vX.Y.Z
#
# For example:
#
#     Short story ideas - textfiles - Obsidian v1.4.16
#
note_title=$(echo "$window_title" \
  | rev \
  | cut -d '-' -f 3- \
  | rev \
  | sed 's/[[:space:]]*$//')

vault_name=$(echo "$window_title" \
  | rev \
  | cut -d'-' -f 2 \
  | rev \
  | sed 's/^[[:space:]]*//' \
  | sed 's/[[:space:]]*$//')

case "$vault_name" in
  "textfiles")
    vault_root=~/textfiles
    ;;
  *)
    echo "Unknown vault name" >&2
    exit 1
    ;;
esac

find "$vault_root" -name "$note_title*" -print | head -n 1
