#!/usr/bin/env bash
# This script checks to see if Docker is running, and if not, it starts
# Docker.
#
# This is a prefix to several of my scripts that rely on Docker being
# present; it saves me having to start Docker myself.

set -o errexit
set -o nounset

if ! docker info > /dev/null 2>&1; then
  echo "Starting Docker..."
  open /Applications/Docker.app

  for i in $(seq 60)
  do
    if docker info > /dev/null 2>&1; then
      break
    fi
    sleep 1
  done
fi
