#!/usr/bin/env bash

set -o errexit
set -o nounset

_ensure_docker_is_running

# Note: the --platform line is to silence this warning on Apple Silicon:
#
#     WARNING: The requested image's platform (linux/amd64) does not
#     match the detected host platform (linux/arm64/v8) and
#     no specific platform was requested
#
# Hopefully at some point cloc will start publishing ARM-based Docker images,
# but until then it's not a big issue -- this isn't a CPU-intensive tool.
docker run --rm \
  --volume $(pwd):$(pwd) \
  --workdir $(pwd) \
  --platform linux/amd64 \
  aldanial/cloc "$@"
