#!/usr/bin/env bash

set -o errexit
set -o nounset

is_docker_running() {
  if /usr/local/bin/docker info > /dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

if ! is_docker_running; then
  echo "Starting Docker..."
  open /Applications/Docker.app

  for i in $(seq 60)
  do
    if is_docker_running; then
      break
    fi
    sleep 1
  done
fi

/usr/local/bin/docker "$@"
