#!/usr/bin/env bash

set -o errexit
set -o nounset

if ! /usr/local/bin/docker info > /dev/null 2>&1; then
  echo "Starting Docker..."
  open /Applications/Docker.app

  for i in $(seq 60)
  do
    if /usr/local/bin/docker info > /dev/null 2>&1; then
      break
    fi
    sleep 1
  done
fi

/usr/local/bin/docker "$@"
