#!/usr/bin/env bash
# A wrapper around the Ruby linter/formatter 'rubocop'.
#
# This runs Rubocop inside a Docker container so I don't have to maintain
# a working Ruby runtime on macOS.

set -o errexit
set -o nounset

if ! docker images | grep alexwlchan/rubocop >/dev/null
then
  pushd ~/repos/scripts/docker
    docker build \
      --tag alexwlchan/rubocop \
      --file rubocop.Dockerfile \
      .
  popd
fi

docker run \
  --volume $(pwd):/working \
  --workdir /working \
  alexwlchan/rubocop "$@"
