#!/usr/bin/env bash
# When I add an entry to my book tracker, I typically commit two files:
#
#   - the Markdown file containing my review
#   - the image of the book's cover
#
# This script looks at the currently staged files, works out the title
# of the book I just reviewed, and creates a commit message for my
# Git commit.

set -o errexit
set -o nounset

pushd ~/repos/books.alexwlchan.net >/dev/null
    markdown_file=$(git diff --cached --name-only | grep ".md$" | head -n 1)
    title=$(grep 'title:' "$markdown_file" | head -n 1 | sed 's/^ *title: *//')
    echo -n "Add review for \"$title\""
popd >/dev/null
