#!/usr/bin/env bash
# Create a commit message for my TIL (Today-I-Learned) repo.

set -o errexit
set -o nounset

pushd ~/repos/til >/dev/null
    markdown_file=$(git diff --cached --name-only | grep -v README.md | head -n 1)
    title=$(basename "$markdown_file")

    # Strip trailing double quotes from the end
    title="${title%\"}"

    # Strip the .md file extension
    title="${title%.md}"

    # Use printf rather than echo so it prints Unicode escapes,
    # e.g. "that\342\200\231s" ~> "that’s"
    printf "Add a new TIL: \"%b\"" "$title"
popd >/dev/null
