#!/usr/bin/env bash
# Create a commit message for my TIL (Today-I-Learned) repo.

set -o errexit
set -o nounset

pushd ~/repos/til >/dev/null
    markdown_file=$(git diff --cached --name-only | head -n 1)

    title=$(grep 'title:' "$markdown_file" | sed 's/^title: //')

    # Use printf rather than echo so it prints Unicode escapes,
    # e.g. "that\342\200\231s" ~> "that’s"
    printf "Add a new TIL: \"%b\"" "$title"
popd >/dev/null
