#!/usr/bin/env bash
# This provides a thin wrapper around the AWS CLI, and prefaces it by
# ensuring I have up-to-date credentials.
#
# It relies on:
#
#   1. This script being before the regular AWS CLI in my $PATH
#   2. Having the AWS CLI installed in the same dir across machines
#

set -o errexit
set -o nounset

_ensure_aws_credentials_are_fresh

python3 -m awscli "$@"
