#!/usr/bin/env bash
# Copy an image from my open browser tab into my book tracker.
#
# This is very specific to my setup and unlikely to be useful to anyone else.

set -o errexit
set -o nounset

LATEST_REVIEW=$(git ls-files -o --exclude-standard)

if [[ "$LATEST_REVIEW" = "" ]]
then
  echo "Please create the review file before you copy the cover image!" >&2
  exit 1
fi

echo "$LATEST_REVIEW"

filename=$(basename -- "$LATEST_REVIEW" .md)
year=$(basename -- $(dirname -- "$LATEST_REVIEW"))

url="$(/Users/alexwlchan/.cargo/bin/safari url)"

image_filename=$(basename -- "$url")
image_extension="${image_filename##*.}"

image_path=~/repos/books.alexwlchan.net/src/covers/$year/$filename.$image_extension

mkdir -p "$(dirname "$image_path")"

echo "$image_path"
curl "$url" > "$image_path"
dominant_colours "$image_path"
