#!/usr/bin/env python3
"""
A script that converts images to an sRGB colour profile.

This is particularly useful for screenshots on macOS, which are taken
with the display's colour profile (e.g. Display LCD or Display P3), but
which I want to convert to sRGB for converting on the web.

Based on https://github.com/python-pillow/Pillow/issues/1662
"""

import os
import sys
import tempfile

from PIL import Image, ImageCms


if __name__ == "__main__":
    try:
        path = sys.argv[1]
    except IndexError:
        sys.exit(f"Usage: {__file__} <PATH>")

    in_img = Image.open(path)

    srgb_profile = ImageCms.createProfile("sRGB")

    _, icc_profile = tempfile.mkstemp(suffix=".icc")
    with open(icc_profile, "wb") as out_file:
        out_file.write(in_img.info.get("icc_profile"))

    out_img = ImageCms.profileToProfile(
        in_img, inputProfile=icc_profile, outputProfile=srgb_profile
    )

    out_img.save(path)
