#!/usr/bin/env bash
# This is a wrapper around @lunasorcery's tool for printing out
# raw Unicode codepoints: see https://github.com/lunasorcery/utf8info

set -o errexit
set -o nounset

if ! docker images | grep lunasorcery/utf8info >/dev/null
then
  pushd ~/repos/pathscripts/text
    docker build \
      --tag lunasorcery/utf8info \
      --file utf8info.Dockerfile \
      .
  popd
fi

docker run --interactive lunasorcery/utf8info
