#!/usr/bin/env bash
# r(esumable) curl.
#
# This just calls curl with a couple of flags that allow it to resume
# an in-progress download.

set -o errexit
set -o nounset

curl \
  --location \
  --remote-name \
  --continue-at - \
  "$1"
